# Generated by Django 5.1.5 on 2025-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myurl',
            name='isCustom',
            field=models.BooleanField(default=False),
        ),
    ]
